### PR TITLE
Performance fix and extensionmethod additions

### PR DESCRIPTION
**Pull request by andersjarl**
**Performance boost for multivalue fields**
Instead of using double foreach loops, use Linq Except which is a lot faster. Especially when there are a lot of values in the multivalue field.

### CODE REVIEW

**Comment by ryannewington** [comment]
Hi @andersjarl, Thanks for submitting the pull request. It's always good to have contributions from others!

I've had a look at this example, as well as the reference source code for the `Except` iterator 
https://github.com/Microsoft/referencesource/blob/master/System.Core/System/Linq/Enumerable.cs#L785

Internally, the except iterator is also doing two foreach loops, but it does not break from the loop like the current code does. Technically, the current implementation should be faster than the `Except` method, as we break out of the inner loop when we find a match. 

Have you seen evidence to the contrary (eg measureable performance improvement doing it this way)? It certainly looks a LOT cleaner, but I fear it could be slower for very large multi-valued sets.

Cheers,

Ryan

**Comment by andersjarl** [comment]
Hi Ryan,

You are correct that it also makes two foreach loops.

The first loop creates an internal Set, (kind of like an HashSet which also requires IEqualityComparer to be implemented to work correctly), for the second list with the values to be excluded.

The second loop (which is not inside the first loop) goes over the first list to see if the value can be added in the already existing Set. If it can then it’s a valid value. If it can’t it’s not and the loop continues.

So this means that it will loop over both lists but only once and the number of iterations will be number of items in second list + number of items in first list.

Also note that since it’s comparing in a HashSet it’s superfast to see if the item exists or not.

Now the existing code in AttributeValue.cs looks roughly like this:
foreach (int newValue in this.newValueList)
{
  bool found = false;
  foreach (int initialValue in initialValueList)
  {
    if (int.Equals(initialValue, newValue))
    {
      found = true;
      break;
    }
  }
  if (!found)
  {
    foundNewValues.Add(newValue);
  }
}

This will loop over the first list and then check if that value exists in the second list by also looping that for every time.

The number of iterations will then theoretically be first list multiplied with second list which will result in an exponential curve (as my tests will show below).

Ofcourse depending on how many values in the inner list that matches the outer list, the loops will be fewer.

Also remember that the lists then are compared again the other way around since it’s searching both for items to add and items to remove!

Now, if the number of changes are few in a large multivalue field this has a huge impact.

The more values in the multivalue field, the more performance gain you get by using Except.

I made separate tests for just this bit of code.

I generate 10000 integers in a list, make a copy of it before I change anything, then I remove 100 random numbers in the list and also add 100 integers that wasn’t already existing.

This means that the loops need to find 100 adds and 100 deletes.

For 10000 integers, 100 adds, 100 removes:
Result with existing foreach loops: 1.8-1.9 seconds
Result with Except: 0.000000 seconds (hardly measurable)

For 20000 integers, 100 adds, 100 removes:
Result with existing foreach loops: 7.6 seconds
Result with Except: 0.000002 seconds (hardly measurable)

For 30000 integers, 100 adds, 100 removes:
Result with existing foreach loops: 16.8 seconds
Result with Except: 0.000002 seconds (still hardly measurable)

For 40000 integers, 100 adds, 100 removes:
Result with existing foreach loops: 30.3 seconds
Result with Except: 0.000002 seconds (still hardly measurable)

For 60000 integers, 100 adds, 100 removes:
Result with existing foreach loops: 68.3 seconds
Result with Except: 0.000002 seconds (still hardly measurable)

For 80000 integers, 100 adds, 100 removes:
Result with existing foreach loops: 119 seconds
Result with Except: 0.000002 seconds (still hardly measurable)

I welcome you to do tests of your own. 

I’ve done tests with the code that I submitted and all seems to work fine.
Leo Erlandsson, who you’ve been in contact with aswell, is my colleague and he has also been involved in the tests.

Regards
Anders

**Comment by ryannewington** [comment]
My apologies, you're 100% right. Thanks for taking the time to walk me though it. I'm filing this as a bug as that performance is not acceptable!

I'll merge and release an update in a day or two. I've got some other changes I am finalizing at the moment and will merge this in after that commit.

**Comment by andersjarl** [comment]
No problem Ryan. Thanks for a fast response!

**Comment by andersjarl** [comment]
Added extensionmethods in this pullrequest aswell.

**Comment by ryannewington** [comment]
Hi @andersjarl,

The pull request is a bit tricky to merge because for some reason, its showing as a delete of all lines in the file, and then an add of all lines

See: https://github.com/lithnet/resourcemanagement-client/pull/8/files

Any idea why this has happened?

Ryan

**Comment by ryannewington** [comment]
I think your files have a UTF8 byte-order mark at the start of them. Can you resubmit without that?

**Comment by andersjarl** [comment]
I tried several things but it didn't work, so it ended with me deleting the fork and starting a new one with your updates.
I made the changes and used TortoiseGit now to push the changes and made a new pull request as you can see. So ignore this one.
I am a SVN user and not a Git user so I am not used to this...

**Comment by ryannewington** [comment]
Implemented in #10

**Pull request closed without merging**
